name: PR

on:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple script
        run: |
          echo "Hello from GitHub Actions!"
          echo "Running on $(uname -a)"
